# Generated by Django 5.0.1 on 2024-02-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=128)),
                ('contacts', models.ManyToManyField(related_name='events', to='contact.contact')),
            ],
            options={
                'unique_together': {('title', 'description', 'date_time', 'location')},
            },
        ),
    ]
